### ISSUE TITLE
Fable support

### ISSUE THREAD

**Issue by eagle-k** [tatsuya-midorikawa/Funtom.Linq#7]
Are there any plans to remove the `System.Linq` dependency in this project?

If that is one of the goals of this project, it may be possible to make this library [Fable compiler compatible](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/docs/docs/dotnet/compatibility.md) (as a side effect).

**Comment by tatsuya-midorikawa** [comment]
Hi, @eagle-k !

One of my golas is remove the dependency on `System.Linq`.  
On the other hand, `Funtom.Linq` has as one of its goals to perform almost as well as or better than `System.Linq`.  

`System.Linq,Select` method has been strongly optimized by C# complier at this time.  
Therefore, simply rewriting code written in C# in F# will not give equivalent performance.  
Until this issue is resolved, I think it will be difficut to remove the dependency on `System.Linq`.

Thanks,
midoliy

**Comment by tatsuya-midorikawa** [comment]
Sorry, I was mistaken about the above.

`ToArray()` was used to measure the performance, but it turned out that simply rewriting the code in F# did not give the same performance as C# because of the speedup in `Select.SpeedOpt.cs.`
Therefore, I think we can remove the dependency on 'System.Linq' completely by porting this part to 'Funtom.Linq' as well.

I will be working on this in v0.0.6.
Please wait for a while.

Thanks,
midoliy
